### PR TITLE
Introduce `is_deferred` convenience function

### LINKED ISSUE #49: Utility to check if a module needs to be materialized
**Is your feature request related to a problem? Please describe:**
Add a function to check whether a `nn.Module` should be materialized.

**Describe the solution you would like:**
```python
from torchdistx.deferred_init import is_deferred
# where
def is_deferred(module: nn.Module) -> bool:
    ...
```

**Describe the alternatives you have considered:**
I could copy the `materialize_module` implementation and loop over all parameters and buffers to check whether `is_fake` returns True for any of the tensors. But IMO this should be provided by this library to make sure the recursive logic always matches

**Additional context:**
This would be used in https://github.com/Lightning-AI/lightning/pull/13868, where the `Trainer` would materialize the module for the user.

### PR DESCRIPTION
**Pull request by cbalioglu**
This PR introduces a convenience helper function `is_deferred`, that returns a boolean value indicating whether a provided tensor or module has been constructed in a deferred-init context.

Fixes #49

### CODE REVIEW

**Comment by cbalioglu** [comment]
cc @carmocca, @tchaton

**Review by carmocca — APPROVED** [review]
Great!

**Review by H-Huang — APPROVED** [review]
LGTM

**Review by rohan-varma — APPROVED** [review]
thanks! this will make it easier for FSDP to check if the module is deferred, which we are currently doing via `any(fake.is_fake(t) for t in module.parameters())`!

**Pull request merged**
