### PR TITLE
Add ShardedTensor SPMD checkpointing API.

### PR DESCRIPTION
**Pull request by kumpera**
Co-authored-by: Wen Zhang <zhangwen@fb.com>

**What does this PR do? Please describe:**
This is the initial code drop for the ShardedTensor based distributed checkpoint API.

**Check list:**
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**?
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you **update the [CHANGELOG](https://github.com/pytorch/torchdistx/blob/main/CHANGELOG.md)**? (not for typos, docs, or minor internal changes)

### CODE REVIEW

**Comment by kumpera** [comment]
We lack the necessary documentation for this feature. This will be addressed in follow up PRs.
I have reviewed docstrings for the public API but we need a proper doc page for the feature and some examples of how to use it.

**Comment by zzzwen** [comment]
Reviewed on diff already

**Comment by zzzwen** [comment]
@cbalioglu, I do not have the permission, do you mind stamp it?

**Review by cbalioglu — APPROVED** [review]

**Comment by cbalioglu** [comment]
@zzzwen @kumpera Do you mind updating [CODEOWNERS](https://github.com/pytorch/torchdistx/blob/main/.github/CODEOWNERS) with:

```
/src/python/torchdistx/checkpoint/ @kumpera @zzzwen 
```

so that for any future PRs you will be considered the authoritative reviewer?

**Comment by kumpera** [comment]
> @zzzwen @kumpera Do you mind updating [CODEOWNERS](https://github.com/pytorch/torchdistx/blob/main/.github/CODEOWNERS) with:
> 
> ```
> /src/python/torchdistx/checkpoint/ @kumpera @zzzwen 
> ```
> 
> so that for any future PRs you will be considered the authoritative reviewer?

Done.

**Review by cbalioglu — APPROVED** [review]

**Pull request merged**
