### PR TITLE
Move optimizers to the Python dir

### PR DESCRIPTION
**Pull request by cbalioglu**
This PR moves the `optimizers` directory to the right location so that `import torchdistx.optimizers.anyprecision_optimizer` works as expected.

### CODE REVIEW

**Review by H-Huang — APPROVED** [review]
Thanks!

**Comment by cbalioglu** [comment]
@stas00 merged. Tomorrow's nightly build should have this fix, but let me know if this is blocking you and I can kick off that build earlier.

**Comment by stas00** [comment]
tomorrow is perfectly fine - thank you, Can!

**Comment by cbalioglu** [comment]
You are welcome.

**Pull request merged**
